"""Migrate tables

Revision ID: f686d06eb574
Revises: 
Create Date: 2024-01-06 20:58:38.112152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f686d06eb574'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_revenue',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('nomenclature_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('sum', sa.DECIMAL(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_revenue_id'), 'department_revenue', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('tax_payer_id', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('role_codes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('role_code', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('supplier', sa.Boolean(), nullable=True),
    sa.Column('employee', sa.Boolean(), nullable=True),
    sa.Column('client', sa.Boolean(), nullable=True),
    sa.Column('representStore', sa.Boolean(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nomenclature_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nomenclature_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('num', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('accountingCategory_id', sa.String(), nullable=True),
    sa.Column('departments_visibility', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nomenclatures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('accounting_category', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('num', sa.String(), nullable=True),
    sa.Column('code', sa.BIGINT(), nullable=True),
    sa.Column('main_unit', sa.String(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('place_type', sa.String(), nullable=True),
    sa.Column('included_in_menu', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('unit_weight', sa.DECIMAL(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('shift_id', sa.String(), nullable=True),
    sa.Column('order_type_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('payment_type_id', sa.String(), nullable=True),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('payment_type_group', sa.String(), nullable=True),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('nomenclature_id', sa.String(), nullable=True),
    sa.Column('nomenclature', sa.String(), nullable=True),
    sa.Column('nomenclature_sum', sa.DECIMAL(), nullable=True),
    sa.Column('nomenclature_amount', sa.DECIMAL(), nullable=True),
    sa.Column('nomenclature_sum_with_discount', sa.DECIMAL(), nullable=True),
    sa.Column('discount_sum', sa.DECIMAL(), nullable=True),
    sa.Column('increase_sum', sa.DECIMAL(), nullable=True),
    sa.Column('full_sum', sa.DECIMAL(), nullable=True),
    sa.Column('measure_unit', sa.String(), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_with_dish_id', sa.String(), nullable=True),
    sa.Column('sold_with_item_id', sa.String(), nullable=True),
    sa.Column('cashier_id', sa.String(), nullable=True),
    sa.Column('guest_num', sa.Integer(), nullable=True),
    sa.Column('guest_card', sa.String(), nullable=True),
    sa.Column('card_num', sa.String(), nullable=True),
    sa.Column('bonus_card', sa.String(), nullable=True),
    sa.Column('counteragent', sa.String(), nullable=True),
    sa.Column('order_discount_type_id', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('order_increase_type_id', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    op.create_table('reference_units',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_list',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=True),
    sa.Column('fiscal_number', sa.Integer(), nullable=True),
    sa.Column('cash_reg_number', sa.Integer(), nullable=True),
    sa.Column('cash_reg_serial', sa.String(), nullable=True),
    sa.Column('open_date', sa.DateTime(), nullable=True),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.Column('accepted_date', sa.DateTime(), nullable=True),
    sa.Column('manager_id', sa.String(), nullable=True),
    sa.Column('responsible_user_id', sa.String(), nullable=True),
    sa.Column('session_start_cash', sa.DECIMAL(), nullable=True),
    sa.Column('pay_orders', sa.DECIMAL(), nullable=True),
    sa.Column('sum_write_off_orders', sa.DECIMAL(), nullable=True),
    sa.Column('sales_cash', sa.DECIMAL(), nullable=True),
    sa.Column('sales_credit', sa.DECIMAL(), nullable=True),
    sa.Column('sales_card', sa.DECIMAL(), nullable=True),
    sa.Column('pay_in', sa.DECIMAL(), nullable=True),
    sa.Column('pay_out', sa.DECIMAL(), nullable=True),
    sa.Column('pay_income', sa.DECIMAL(), nullable=True),
    sa.Column('cash_remain', sa.DECIMAL(), nullable=True),
    sa.Column('cash_diff', sa.DECIMAL(), nullable=True),
    sa.Column('session_status', sa.String(), nullable=True),
    sa.Column('conception_id', sa.String(), nullable=True),
    sa.Column('point_of_sale_id', sa.String(), nullable=True),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_remains',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(), nullable=True),
    sa.Column('nomenclature_id', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('sum', sa.DECIMAL(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_remains_id'), 'store_remains', ['id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stores')
    op.drop_index(op.f('ix_store_remains_id'), table_name='store_remains')
    op.drop_table('store_remains')
    op.drop_table('shift_list')
    op.drop_table('reference_units')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('nomenclatures')
    op.drop_table('nomenclature_groups')
    op.drop_table('nomenclature_categories')
    op.drop_table('employees')
    op.drop_table('employee_roles')
    op.drop_table('departments')
    op.drop_index(op.f('ix_department_revenue_id'), table_name='department_revenue')
    op.drop_table('department_revenue')
    # ### end Alembic commands ###
